package org.zafritech.zidingorms.commons.enums;

public enum ItemStatus {

    NONE, CREATED, ACCEPTED, DELETED, DEFERRED, COMPLETED, WITHDRAWN, REJECTED, VERIFIED, IMPLEMENTED, APPROVED, OPEN, CLOSED, SELECTED, DEFINED, CONFIRMED
}
